language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - cat server.js
  - docker --version # print the version for logging
  - docker build -t travis-of-the-cosmos .
  - docker tag travis-of-the-cosmos mjenison/travis-of-the-cosmos:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mjenison/travis-of-the-cosmos
